EMOTION_SYNONYMS = {
    "admiration": ["respect", "veneration", "appreciation"],
    "amusement": ["delight", "enjoyment"],
    "anger": ["rage", "outrage"],
    "annoyance": ["irritation", "displeasure"],
    "anticipation": ["expectation"],
    "approval": ["acceptance", "agreement"],
    "caring": ["kind", "tender", "kindhearted"],
    "confusion": ["uncertainty", "doubt"],
    "curiosity": ["interest"],
    "desire": ["inclination", "preference"],
    "disappointment": ["chagrin"],
    "disapproval": ["objection", "disagreement"],
    "disgust": ["revulsion", "aversion", "distaste"],
    "embarrassment": ["awkwardness", "unease", "discomfort"],
    "excitement": ["exhilaration", "enthusiasm"],
    "fear": ["terror", "alarm", "worry", "angst"],
    "gratitude": ["acknowledgment", "regard"],
    "grief": ["sorrow", "misery"],
    "joy": ["delight", "jubilation"],
    "love": ["fondness", "intimacy", "adoration", "worship"],
    "nervousness": ["anxiety", "tension", "stress"],
    "optimism": ["confidence", "cheerfulness"],
    "pessimism": ["nagativity", "gloom", "hopelessness"],
    "pride": ["honor", "ego", "nationalism", "self-esteem"],
    "realization": ["awareness", "understanding", "perception"],
    "relief": ["comfort", "reassurance"],
    "remorse": ["contrition", "repentance"],
    "sadness": ["unhappiness", "misery"],
    "surprise": ["shock", "revelation"],
    "trust": ["faith", "belief"],
    "despair": ["desperation", "anguish", "despondency"],
    "hate": ["loathing", "abhorrence", "hostility"],
    "contempt": ["disrespect", "scorn"],
    "guilt": ["culpability", "wrongdoing"],
    "shame": ["humiliation", "indignity"],
    "hope": ["wish", "ambition", "dream"],
    "happiness": ["gladness", "satisfaction", "well-being"],
    "sarcasm": ["irony", "satire", "mockery"],
    "positive": [],
    "negative": [],
}
